### ISSUE TITLE
few checks still pending, undericeNP.R, following chla and aggregation edits

### ISSUE THREAD

**Issue by st3powers** [st3powers/UndericeBGC#4]
note to self!

-Check to make sure stations are being aggregated appropriately, without lumping, esp downstream of the new chl a merge

-Make sure the data NP output files have not changed, with today's updates

-Confirm what is difference between o2 and o2_sum, in data.NP.shallow/deep/middle

-Add new comments to undericeNP.R script

**Comment by stephlabou** [comment]
o2_sum is mean(O2_auc (area under curve for oxygen vs depth) / depth of lake)

Think need to move up in script where we restrict samples (e.g. end points of data.agg.orig for iceon season used to subset all the data) - otherwise "winteryear" is quite misleading (e.g. July of preceding year is in no way part of next winter year). Plus, later things are grouped by winteryear, which is going to throw off these monthly O2 summaries calculated right below winteryear calc.
